/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.spacelib.borneusager;

import fr.miage.spacelib.utilities.RMIBorneServiceManager;
import fr.miage.spacelib.vspaceshared.utilities.ReservationExport;
import fr.miage.spacelib.vspaceshared.utilities.UsagerExport;
import javax.swing.JFrame;
import fr.miage.spacelib.vspaceshared.interfremote.ExpoGestionBorneRemote;
import fr.miage.spacelib.vspaceshared.utilities.AucunUsagerException;
import fr.miage.spacelib.vspaceshared.utilities.AucunVoyageException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;

/**
 *
 * @author AlexisVivier
 */
public class JFConnexion extends javax.swing.JFrame {

    final public Long STATION_ID = 10L;

    private static JFConnexion pageConnexion;

    private ExpoGestionBorneRemote borne;

    private UsagerExport usager;

    private ReservationExport reservation;

    public ExpoGestionBorneRemote getBorne() {
        return borne;
    }

    public ReservationExport getReservation() {
        return reservation;
    }

    public void setReservation(ReservationExport reservation) {
        this.reservation = reservation;
    }

    public UsagerExport getUsager() {
        return usager;
    }

    public void setUsager(UsagerExport usager) {
        this.usager = usager;
    }

    public static JFConnexion getPageConnexion() {
        return pageConnexion;
    }

    /**
     * Creates new form JFEmpruntNavette
     */
    public JFConnexion() {
        pageConnexion = this;
        initComponents();
        lbl_bienvenue.setText("Bienvenue à la station " + STATION_ID);
        init();
    }

    private void init() {
        try {
            RMIBorneServiceManager rmiMgr = new RMIBorneServiceManager();
            this.borne = rmiMgr.getClientLourdRemoteSvc();
        } catch (NamingException ex) {
            Logger.getLogger(JFConnexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_connexion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_bienvenue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txb_identifiantClient = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txb_nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txb_prenom = new javax.swing.JTextField();
        btn_inscription = new javax.swing.JButton();
        label_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VISIOSPACE: CONNEXION");
        setPreferredSize(new java.awt.Dimension(350, 350));
        setResizable(false);

        btn_connexion.setText("CONNEXION");
        btn_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connexionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CONNEXION USAGER");

        lbl_bienvenue.setText("jLabel3");

        jLabel4.setText("Identifiant client");

        txb_identifiantClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txb_identifiantClientActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom");

        jLabel3.setText("Prenom");

        btn_inscription.setText("INSCRIPTION");
        btn_inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_connexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txb_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txb_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txb_identifiantClient, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_inscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_bienvenue)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bienvenue)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txb_identifiantClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_connexion)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txb_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txb_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_inscription)
                .addGap(18, 18, 18)
                .addComponent(label_error, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connexionActionPerformed
        boolean etatConnexion = false;
        try {
            usager = borne.connecter(Long.parseLong(txb_identifiantClient.getText()));
            etatConnexion = true;
        } catch (AucunUsagerException ex) {
            Logger.getLogger(JFConnexion.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (etatConnexion) {
            try {

                reservation = borne.reservationEnCours(usager.getId());

                JFrame frame = new JFDepartArrivee();
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(300, 400);
                frame.setVisible(true);

                this.dispose();
            } catch (AucunVoyageException ex) {
                
                /* Ouvrir nouvelle fenêtre */
                JFrame frame = new JFEmpruntNavette();
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(300, 400);
                frame.setVisible(true);

                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_connexionActionPerformed

    private void txb_identifiantClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txb_identifiantClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txb_identifiantClientActionPerformed

    private void btn_inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscriptionActionPerformed
        usager = borne.inscrire(txb_nom.getText(), txb_prenom.getText());
        txb_identifiantClient.setText(Long.toString(usager.getId()));
    }//GEN-LAST:event_btn_inscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_connexion;
    private javax.swing.JButton btn_inscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_error;
    private javax.swing.JLabel lbl_bienvenue;
    private javax.swing.JTextField txb_identifiantClient;
    private javax.swing.JTextField txb_nom;
    private javax.swing.JTextField txb_prenom;
    // End of variables declaration//GEN-END:variables
}
