/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.spacelib.borneusager;

import fr.miage.spacelib.utilities.RMIBorneServiceManager;
import fr.miage.spacelib.vspaceshared.interfremote.ExpoGestionBorneRemote;
import fr.miage.spacelib.vspaceshared.utilities.AucunQuaiException;
import fr.miage.spacelib.vspaceshared.utilities.AucunVoyageException;
import fr.miage.spacelib.vspaceshared.utilities.AucuneNavetteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JFrame;

/**
 *
 * @author AlexisVivier
 */
public class JFDepartArrivee extends javax.swing.JFrame {

    ExpoGestionBorneRemote borne;
    
    /**
     * Creates new form JFEmpruntNavette
     */
    public JFDepartArrivee() {
        initComponents();
        lbl_bienvenue.setText("Bienvenue à la station " + JFConnexion.getPageConnexion().STATION_ID);
        init();
    }

    private void init() {
        try {
            RMIBorneServiceManager rmiMgr = new RMIBorneServiceManager();
            this.borne = rmiMgr.getClientLourdRemoteSvc();
            System.out.println(JFConnexion.getPageConnexion().getUsager().getId().toString());
            
            if (this.borne.reservationEnCours(JFConnexion.getPageConnexion().getUsager().getId()) == null) {
                
                btn_depart.setEnabled(false);
                btn_arrivee.setEnabled(false);
            }
            
        } catch (NamingException ex) {
            Logger.getLogger(JFConnexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucunVoyageException ex) {
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
            btn_depart.setEnabled(false);
            btn_arrivee.setEnabled(false);
            label_error.setText("Aucun voyage n'est prévu aujourd'hui !");
            label_info.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_okay = new javax.swing.JButton();
        lbl_bienvenue = new javax.swing.JLabel();
        btn_depart = new javax.swing.JButton();
        btn_arrivee = new javax.swing.JButton();
        label_error = new javax.swing.JLabel();
        label_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EMBARQUEMENT");

        btn_okay.setText("RETOUR A L'ACCUEIL");
        btn_okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okayActionPerformed(evt);
            }
        });

        lbl_bienvenue.setText("jLabel3");

        btn_depart.setText("Départ");
        btn_depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_departActionPerformed(evt);
            }
        });

        btn_arrivee.setText("Arrivée");
        btn_arrivee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arriveeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lbl_bienvenue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_error, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_arrivee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_depart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_okay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                            .addComponent(label_info, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bienvenue)
                .addGap(23, 23, 23)
                .addComponent(btn_depart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_arrivee)
                .addGap(18, 18, 18)
                .addComponent(label_info, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(label_error, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn_okay)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okayActionPerformed
        /* Ouvrir nouvelle fenêtre */
        JFrame frame = new JFConnexion();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 400);
        frame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_okayActionPerformed

    private void btn_departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_departActionPerformed
        try {
            borne.departVoyage(JFConnexion.getPageConnexion().getReservation().getId());
            label_info.setText("Décollage de la navette !");
            if (this.borne.isReservationArrivee(JFConnexion.getPageConnexion().getUsager().getId())) {
                btn_depart.setEnabled(true);
                btn_arrivee.setEnabled(false);
            } else {
                btn_depart.setEnabled(false);
                btn_arrivee.setEnabled(true);
            }
        } catch (AucunVoyageException ex) {
            label_error.setText("Aucun voyage n'est prévu aujourd'hui !");
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucuneNavetteException ex) {
            label_error.setText(ex.getMessage());
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucunQuaiException ex) {
            label_error.setText(ex.getMessage());
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_departActionPerformed

    private void btn_arriveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arriveeActionPerformed
        try {
            borne.arriveeVoyage(JFConnexion.getPageConnexion().getReservation().getId());
            label_info.setText("La navette est arrivée à destination");
            btn_depart.setEnabled(false);
            btn_arrivee.setEnabled(false);
        } catch (AucunVoyageException ex) {
            label_error.setText(ex.getMessage());
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucuneNavetteException ex) {
            label_error.setText(ex.getMessage());
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucunQuaiException ex) {
            label_error.setText(ex.getMessage());
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_arriveeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDepartArrivee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDepartArrivee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDepartArrivee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDepartArrivee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDepartArrivee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arrivee;
    private javax.swing.JButton btn_depart;
    private javax.swing.JButton btn_okay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_error;
    private javax.swing.JLabel label_info;
    private javax.swing.JLabel lbl_bienvenue;
    // End of variables declaration//GEN-END:variables
}
