/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.spacelib.borneusager;

import fr.miage.spacelib.utilities.RMIBorneServiceManager;
import fr.miage.spacelib.vspaceshared.interfremote.ExpoGestionBorneRemote;
import fr.miage.spacelib.vspaceshared.utilities.AucunQuaiException;
import fr.miage.spacelib.vspaceshared.utilities.AucunVoyageException;
import fr.miage.spacelib.vspaceshared.utilities.AucuneNavetteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JFrame;

/**
 *
 * @author AlexisVivier
 */
public class JFDepartArrivee extends javax.swing.JFrame {

    ExpoGestionBorneRemote borne;

    /**
     * Creates new form JFEmpruntNavette
     */
    public JFDepartArrivee() {
        initComponents();
        lbl_bienvenue.setText("Bienvenue à la station " + JFConnexion.STATION_ID);
        init();
    }

    private void init() {
        try {
            RMIBorneServiceManager rmiMgr = new RMIBorneServiceManager();
            this.borne = rmiMgr.getClientLourdRemoteSvc();
            this.borne.testNul("TTITI");
        } catch (NamingException ex) {
            Logger.getLogger(JFConnexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        lbl_bienvenue = new javax.swing.JLabel();
        btn_depart = new javax.swing.JButton();
        btn_arrivee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EMBARQUEMENT");

        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        lbl_bienvenue.setText("jLabel3");

        btn_depart.setText("Départ");
        btn_depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_departActionPerformed(evt);
            }
        });

        btn_arrivee.setText("Arrivée");
        btn_arrivee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arriveeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_arrivee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_depart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lbl_bienvenue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_bienvenue)
                .addGap(23, 23, 23)
                .addComponent(btn_depart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_arrivee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btn_cancel)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        /* Ouvrir nouvelle fenêtre */
        JFrame frame = new JFConnexion();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 300);
        frame.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_departActionPerformed
        try {
            borne.departVoyage(JFConnexion.getReservation().getId());
        } catch (AucunVoyageException ex) {
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucuneNavetteException ex) {
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucunQuaiException ex) {
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_departActionPerformed

    private void btn_arriveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arriveeActionPerformed
        try {
            borne.arriveeVoyage(JFConnexion.getReservation().getId());
        } catch (AucunVoyageException ex) {
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucuneNavetteException ex) {
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AucunQuaiException ex) {
            Logger.getLogger(JFDepartArrivee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_arriveeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDepartArrivee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDepartArrivee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDepartArrivee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDepartArrivee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDepartArrivee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arrivee;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_depart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_bienvenue;
    // End of variables declaration//GEN-END:variables
}
